2020-06-17 14:44:39,439 ERROR: Exception on /login [GET] [in /home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/crystal/atompython/blog3-template/app/routes.py", line 63, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/crystal/atompython/blog3-template/app/templates/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/crystal/atompython/blog3-template/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/crystal/atompython/blog3-template/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/crystal/atompython/blog3-template/app/templates/login.html", line 16, in block "app_content"
    <h5> <i class="fas fa-quote-left"></i> {{random.quote}} <i class="fas fa-quote-right"></i></h5>
  File "/home/crystal/atompython/blog/virtual/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'random' is undefined
2020-06-17 14:47:39,195 INFO: Microblog startup [in /home/crystal/atompython/blog3-template/app/__init__.py:45]
2020-06-17 15:03:10,237 INFO: Microblog startup [in /home/crystal/atompython/blog3-template/app/__init__.py:45]
2020-06-17 15:03:50,622 INFO: Microblog startup [in /home/crystal/atompython/blog3-template/app/__init__.py:45]
2020-06-17 15:05:26,089 INFO: Microblog startup [in /home/crystal/atompython/blog3-template/app/__init__.py:45]
2020-06-17 15:13:06,395 INFO: Microblog startup [in /home/crystal/atompython/blog3-template/app/__init__.py:45]
2020-06-17 15:17:21,821 INFO: Microblog startup [in /home/crystal/atompython/blog3-template/app/__init__.py:45]
2020-06-17 15:17:48,062 INFO: Microblog startup [in /home/crystal/atompython/blog3-template/app/__init__.py:45]
2020-06-17 15:22:17,613 INFO: Microblog startup [in /home/crystal/atompython/blog3-template/app/__init__.py:45]
2020-06-17 15:26:25,608 INFO: Microblog startup [in /home/crystal/atompython/blog3-template/app/__init__.py:45]
2020-06-17 15:39:59,939 INFO: Microblog startup [in /home/crystal/atompython/blog3-template/app/__init__.py:45]
2020-06-17 15:40:57,519 INFO: Microblog startup [in /home/crystal/atompython/blog3-template/app/__init__.py:45]
2020-06-17 16:20:47,646 INFO: Microblog startup [in /home/crystal/atompython/blog233/app/__init__.py:45]
2020-06-17 16:21:42,479 INFO: Microblog startup [in /home/crystal/atompython/blog233/app/__init__.py:45]
